<?php
/**
 * Created by PhpStorm.
 * User: zhangxinrong
 * Date: 2020/8/5
 * Time: 5:48 PM
 */

namespace app\admin\common;

use think\Controller;
use think\Request;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $info = session('user_info');
        define('USER_ID',$info['user_id']);
    }

    protected function isLogin(){
        if (is_null(USER_ID)){
            $this->error('请勿非法登录','login/index');
        }
    }

    protected function existLogin(){
        if (!is_null(USER_ID)){
            $this->success('您已登录成功,请勿重复登录','index/index');
        }
    }

}